local function map(mode, lhs, rhs, desc)
  vim.keymap.set(mode, lhs, rhs, { silent = true, desc = desc })
end

map("n", "<leader>o", "<Cmd>restart<CR>", "Restart Neovim")
map("n", "<leader>w", "<Cmd>write<CR>", "Write buffer")
map("n", "<leader>q", "<Cmd>quit<CR>", "Quit window")
map("n", "<leader>Q", "<Cmd>wqall<CR>", "Write all and quit")
map("n", "<leader>bd", "<Cmd>bdelete<CR>", "Delete buffer")
map("n", "<leader>bp", "<Cmd>bprevious<CR>", "Previous buffer")
map("n", "<leader>bn", "<Cmd>bnext<CR>", "Next buffer")
map("n", "<leader>v", "<Cmd>vsplit<CR>", "Split window vertically")
map("n", "<leader>Wv", "<Cmd>vsplit<CR>", "Split window vertically")
map("n", "<leader>Ws", "<Cmd>split<CR>", "Split window horizontally")
map("n", "<leader>Wq", "<Cmd>close<CR>", "Close window")

map("n", "<C-f>", function()
  vim.ui.open(vim.fn.getcwd())
end, "Open working directory externally")
map("n", "<leader>e", "<Cmd>Oil<CR>", "Explore files")

local function telescope(picker)
  return function()
    require("telescope.builtin")[picker]()
  end
end
map("n", "<leader>f", telescope "find_files", "Find files")
map("n", "<leader>r", telescope "buffers", "Find buffers")
map("n", "<leader>g", telescope "live_grep", "Search text")
map("n", "<leader>sf", telescope "find_files", "Find files")
map("n", "<leader>sg", telescope "live_grep", "Search text")
map("n", "<leader>sh", telescope "help_tags", "Search help")
map("n", "<leader>sr", telescope "oldfiles", "Find recent files")
map("n", "<leader>sd", telescope "diagnostics", "Search diagnostics")

map("n", "<C-h>", "<Cmd>wincmd h<CR>", "Focus left window")
map("n", "<C-j>", "<Cmd>wincmd j<CR>", "Focus lower window")
map("n", "<C-k>", "<Cmd>wincmd k<CR>", "Focus upper window")
map("n", "<C-l>", "<Cmd>wincmd l<CR>", "Focus right window")
map("n", "<C-S-h>", "<Cmd>vertical resize -5<CR>", "Narrow window")
map("n", "<C-S-j>", "<Cmd>resize -5<CR>", "Shorten window")
map("n", "<C-S-k>", "<Cmd>resize +5<CR>", "Heighten window")
map("n", "<C-S-l>", "<Cmd>vertical resize +5<CR>", "Widen window")

map({ "n", "v" }, ";", ":", "Enter command line")
map({ "n", "v" }, ":", ";", "Repeat character search")
map("n", "<Esc>", "<Cmd>nohlsearch<CR>", "Clear search highlighting")

map("n", "gd", vim.lsp.buf.definition, "LSP: Go to definition")
map("n", "gD", vim.lsp.buf.declaration, "LSP: Go to declaration")
map("n", "<leader>ly", vim.lsp.buf.type_definition, "LSP: Go to type definition")
map({ "n", "x" }, "<leader>la", vim.lsp.buf.code_action, "LSP: Code actions")
map("n", "<leader>ln", vim.lsp.buf.rename, "LSP: Rename symbol")
map("n", "<leader>lf", function()
  vim.lsp.buf.format { bufnr = 0, async = true }
end, "LSP: Format buffer")
map("n", "<leader>ls", telescope "lsp_document_symbols", "LSP: Find document symbols")
map("n", "<leader>li", telescope "lsp_implementations", "LSP: Find implementations")
map("n", "<leader>lr", telescope "lsp_references", "LSP: Find references")

map("n", "<leader>lq", "<Cmd>Trouble qflist toggle<CR>", "Trouble: Quickfix list")
map("n", "<leader>ll", "<Cmd>Trouble loclist toggle<CR>", "Trouble: Location list")
map("n", "<leader>lD", "<Cmd>Trouble diagnostics toggle<CR>", "Trouble: Global diagnostics")
map("n", "<leader>ld", "<Cmd>Trouble diagnostics toggle filter.buf=0<CR>", "Trouble: Buffer diagnostics")
